### ISSUE TITLE
Add deployment webhook for gitbook.io or similar

### ISSUE THREAD

**Issue by audreyr** [ceaess/python-installfest#3]
I'm making good progress! It would be nice to build the markdown files into nicely-formatted HTML, so that I can see the output as it would appear on the final installfest site.

For example, http://tutorial.djangogirls.org/ is the nicely-formatted HTML version of https://github.com/DjangoGirls/tutorial. They use gitbook.io which is like ReadTheDocs but for Markdown.

@ceaess this part requires admin rights to webhook settings, so:

* Want to create a gitbook account and set up a deploy hook that links to your account? (Feel free to choose a different tool, if you know of any similar tool for Markdown rendering.)
* Or want to grant me access to the webhook settings?

**Comment by ceaess** [comment]
Fixed with recent gitbook updates
